# Generated by Django 4.1.4 on 2023-08-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_lastmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='lastmessage',
            new_name='status',
        ),
    ]
